---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.app.name }}-pipeline
  labels:
    type: pipeline
    backstage.io/kubernetes-id: {{ .Values.app.name }}
spec:
  params:
  - name: git-url
    default: {{ .Values.git.repo }}
  - name: git-branch
    default: {{ .Values.git.branch }}
  - name: output-image
    description: reference of the image that will get created
    default: {{ include "image.url" . }}
    type: string
  tasks:
  - name: fetch-repository
    params:
      - name: url
        value: $(params.git-url)
      - name: subdirectory
        value: ''
      - name: deleteExisting
        value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: source
  - name: maven
    params:
    - name: GOALS
      value:
      - package
    - name: PROXY_PROTOCOL
      value: http
    - name: CONTEXT_DIR
      value: .
    runAfter:
      - fetch-repository
    taskRef:
      kind: ClusterTask
      name: maven
    workspaces:
      - name: maven-settings
        workspace: maven-settings
      - name: source
        workspace: source
  - name: build-and-push
    params:
      - name: IMAGE
        value: $(params.output-image)
    runAfter:
    - maven
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
      - name: source
        workspace: source
  workspaces:
    - name: source
    - name: maven-settings
