kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.applicationName }}
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    {{- include "java-backend.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    {{- if eq .Values.deploymentStrategy.type "RollingUpdate" }}
    {{- with .Values.deploymentStrategy }}
    rollingUpdate:
      maxSurge: {{ .rollingMaxSurge }}
      maxUnavailable: {{ .rollingMaxUnavailable }}
    {{- end }}
    {{- end }}
    {{- if eq .Values.deploymentStrategy.type "Recreate" }}
    recreateParams:
      timeoutSeconds: {{ .Values.deploymentStrategy.timeout }}
    {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "java-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ .Values.applicationName }}
      labels:
        {{- include "backstage.labels" . | nindent 8 }}
        {{- include "java-backend.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod | default 60 }}
      serviceAccountName: {{ include "java-backend.serviceAccountName" . }}
      containers:
      - name: {{ .Values.applicationName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.port }}
            protocol: TCP
          - containerPort: {{ .Values.portHTTPS }}
            protocol: TCP
          - containerPort: {{ .Values.port8778 }}
            protocol: TCP
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      securityContext: {}