---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.applicationName }}
  labels:
    {{- include "java-backend.labels" . | nindent 4 }}
    {{- include "backstage.labels" . | nindent 4 }}
spec:
  port:
    targetPort: {{ .Values.portName }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.applicationName }}
    weight: 100
  wildcardPolicy: None

