app:
  name: ${{values.component_id}}
  namespace: ${{values.namespace}}
  cluster: ${{values.cluster}}

git:
  branch: main
  repo: ${{values.source_repository}}
  org: ${{values.org}}
  name: ${{values.repository_name}}
  host: ${{values.git_host}}
  token: ''
  webhookSecret: ''

image:
  host: ${{values.image_host}}
  name: ${{values.image_name}}
  tag: ${{values.image_tag}}

host: ""

pipelineStorage:
  pvcSize: 3Gi
  storageClassName: ""

targetEnvironment: dev
env: []
