---
kind: Service
apiVersion: v1
spec:
  ports:
  - name: web
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  selector:
    {{- include "frontend.selectorLabels" $ | nindent 4 }}
metadata:
  name: {{ .Values.applicationName }}
  labels:
    app: {{ .Values.applicationName }}
    {{- include "backstage.labels" . | nindent 4 }}
  annotations:
    description: The web server's http port
