---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.app.name }}-pipeline
  labels:
    type: pipeline
    backstage.io/kubernetes-id: {{ .Values.app.name }}
spec:
  params:
  - name: git-url
    default: {{ .Values.git.repo }}
  - name: git-branch
    default: {{ .Values.git.branch }}
  - name: output-image
    description: reference of the image that will get created
    default: {{ include "image.url" . }}
    type: string
  - default: .
    name: PATH_CONTEXT
    type: string
  - default: 16-ubi8
    name: VERSION
    type: string
  tasks:
  - name: fetch-repository
    params:
      - name: url
        value: $(params.git-url)
      - name: subdirectory
        value: ''
      - name: deleteExisting
        value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: workspace
  - name: build
    params:
      - name: IMAGE
        value: $(params.output-image)
      - name: TLSVERIFY
        value: 'false'
      - name: PATH_CONTEXT
        value: $(params.PATH_CONTEXT)
      - name: VERSION
        value: $(params.VERSION)
    runAfter:
      - fetch-repository
    taskRef:
      kind: ClusterTask
      name: s2i-nodejs
    workspaces:
      - name: source
        workspace: workspace
  workspaces:
    - name: workspace