---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.app.name }}
  labels:
    type: pipeline
    backstage.io/kubernetes-id: ${{values.component_id}}
spec:
  params:
  - name: git-url
    default: {{ .Values.git.repo }}
  - name: git-branch
    default: {{ .Values.git.branch }}
  - name: target-namespace
    default: {{ .Values.app.namespace }}
  - name: output-image
    description: reference of the image that will get created
    default: {{ include "image.url" . }}
    type: string
  tasks:
  - name: fetch-repository
    params:
      - name: url
        value: $(params.git-url)
      - name: subdirectory
        value: ''
      - name: deleteExisting
        value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: shared-workspace
  - name: install-dependencies
    taskRef:
      name: npm
      kind: Task
    runAfter:
      - fetch-repository
    workspaces:
      - name: source
        workspace: shared-workspace
  - name: build-and-push
    params:
      - name: STORAGE_DRIVER
        value: vfs
      - name: IMAGE
        value: $(params.output-image)
      - name: DOCKERFILE
        value: ./Dockerfile
      - name: CONTEXT
        value: .
      - name: TLSVERIFY
        value: "true"
      - name: SKIP_PUSH
        value: "false"
      - name: FORMAT
        value: oci
      - name: BUILDER_IMAGE
        value: registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
    runAfter:
    - install-dependencies
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
      - name: source
        workspace: shared-workspace
  workspaces:
    - name: shared-workspace
