apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  workspaces:
  - name: source
  steps:
    - name: npm-install
      image: registry.redhat.io/ubi8/nodejs-14:latest
      command:
        - /bin/sh
        - -c
      args:
        - npm install --package-lock
      workingDir: $(workspaces.source.path)
