---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ .Values.app.name }}-run-pipeline
spec:
  params:
    - name: git-revision
      description: The git revision
      default: {{ .Values.git.branch }}
    - name: git-repo-url
      description: The repo url
    - name: output-image
      description: reference of the image that will get created
      default: {{ include "image.url" . }}
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: {{ .Values.app.name }}-$(uid)
        labels:
          backstage.io/kubernetes-id:  {{ .Values.app.name }}
      spec:
        params:
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-branch
            value: $(tt.params.git-revision)
          - name: output-image
            value: $(tt.params.output-image)
          - name: PATH_CONTEXT
            value: .
          - name: VERSION
            value: 16-ubi8
        pipelineRef:
          name: {{ .Values.app.name }}-pipeline
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi

