apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id}}
  {%- if values.description %}
  description: ${{values.description}}
  {%- endif %}
  annotations:
    argocd/app-name: ${{values.component_id}}
    backstage.io/kubernetes-id: ${{values.component_id}}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://${{values.host}}/${{values.group}}/${{values.component_id}}
    gitlab.com/project-slug: ${{values.group}}/${{values.component_id}}
    janus-idp.io/tekton:  ${{values.component_id}}
  tags:
    - java
    - vertex
    - maven
    - workshop
  links:
    - url: https://console-openshift-console${{values.cluster_id}}/dev-pipelines/ns/${{values.namespace}}/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console${{values.cluster_id}}/k8s/ns/${{values.namespace}}/deployments/${{values.component_id}}
      title: Deployment
      icon: web
    - url: https://devspaces${{values.cluster_id}}/#https://${{values.host}}/${{values.group}}/${{values.component_id}}?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}
  system: workshop-system-${{values.component_id}}
  providesApis:
    - backend-api-${{values.namespace}}
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-${{values.component_id}}
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
spec:
  owner: ${{values.owner | dump}}
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.component_id}}
  description:  API surface exposed to interact with Backends (catalog and inventory) via the Gateway
  links:
    - url: http://gateway-app-${{values.user_id}}-${{values.namespace}}${{values.cluster_id}}/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://${{values.host}}/${{values.group}}/${{values.component_id}}/-/blob/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: ${{values.user_id | dump}}
  system: workshop-system-${{values.component_id}}
  definition:
    $text: https://${{values.host}}/${{values.group}}/${{values.component_id}}/-/blob/main/src/main/resources/META-INF/openapi.yaml
